# Generated by Django 5.1.7 on 2025-03-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cobranca_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranca',
            name='tipo',
            field=models.CharField(choices=[('PACOTE', 'Pacote'), ('SENHA_EXTRA', 'Senha Extra')], default='PACOTE', max_length=20),
        ),
    ]
