# Generated by Django 5.1.7 on 2025-03-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cobranca_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cobranca',
            old_name='usuario',
            new_name='criado_por',
        ),
    ]
